apiVersion: templates.sitewhere.io/v1alpha3
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-label-generation
  labels:
      sitewhere.io/functional-area: label-generation
spec:
  configuration:
    manager: {}
    generators:
      - id: qrcode
        name: "QR Code Generator"
        type: qr-code
        configuration:
          width: 200
          height: 200
          foregroundColor: 333333ff
          backgroundColor: ffffffff
