apiVersion: v2
appVersion: "2.1.1"
description: Helm chart for SiteWhere core Database components
name: sitewhere-infra-database
version: 0.3.0
keywords:
  - sitewhere
  - internet-of-things
  - open-source
  - iot
  - iot-framework
  - iot-platform
  - platform
  - integration
  - mongodb
home: https://sitewhere.io/
maintainers:
  - name: Derek Adams
    email: derek.adams@sitewhere.com
  - name: Jorge Villaverde
    email: jorge.villaverde@sitewhere.com
icon: http://sitewhere.io/docs/2.0.0/images/favicon.png
dependencies:
  - name: mongodb
    version: 5.2.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: cassandra
    version: 0.10.1
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    condition: sitewhere-infra-database.cassandra.enabled, cassandra.enabled
  - name: influxdb
    version: 3.0.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: sitewhere-infra-database.influxdb.enabled, influxdb.enabled
  - name: warp10
    version: 0.2.3
    repository: https://sitewhere.io/helm-charts
    condition: sitewhere-infra-database.warp10.enabled, warp10.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: sitewhere-infra-database.tenantsdb.enabled, tenantsdb.enabled
    alias: tenantsdb
