apiVersion: v2
name: sitewhere-infrastructure
description: SiteWhere Infrastructure Helm Chart
type: application
version: 0.1.11
appVersion: 3.0.5

keywords:
  - sitewhere
  - internet-of-things
  - open-source
  - iot
  - iot-framework
  - iot-platform
  - platform
  - integration
  - microservices
  - device-management
  - mqtt
  - java
  - arduino
  - raspberry-pi
  - android
  - kafka
  - zookeeper
home: https://sitewhere.io/
maintainers:
  - name: Derek Adams
    email: derek.adams@sitewhere.com
  - name: Jorge Villaverde
    email: jorge.villaverde@sitewhere.com
icon: http://sitewhere.io/docs/2.0.0/images/favicon.png

# Chart depencies
dependencies:
  - name: postgresql
    version: 9.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - infrastructure
  - name: influxdb
    version: 4.8.10
    repository: https://influxdata.github.io/helm-charts
    condition: infrastructure.enabled,influxdb.enabled
    tags:
      - infrastructure
  - name: redis
    version: 12.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - infrastructure
  - name: nifi
    version: 0.3.2
    repository: https://cetic.github.io/helm-charts
    condition: nifi.enabled
    tags:
      - infrastructure
  - name: mosquitto
    version: 0.7.0
    repository: https://k8s-at-home.com/charts/
    condition: mosquitto.enabled
    tags:
      - infrastructure
  - name: strimzi-kafka-operator
    version: 0.21.0
    repository: https://strimzi.io/charts/
    condition: strimzi.enabled
    tags:
      - infrastructure
  - name: keycloak
    version: 9.8.1
    repository: https://codecentric.github.io/helm-charts
    condition: keycloak.enabled
    tags:
      - infrastructure
