apiVersion: templates.sitewhere.io/v1alpha3
kind: InstanceConfigurationTemplate
metadata:
  name: default
spec:
  configuration:
    infrastructure:
      namespace: sitewhere-system
      redis:
        hostname: sitewhere-infrastructure-redis-ha-announce
        port: 26379
        nodeCount: 3
        masterGroupName: sitewhere
      kafka:
        hostname: sitewhere-kafka-kafka-bootstrap
        port: 9092
        defaultTopicPartitions: 8
        defaultTopicReplicationFactor: 3
      metrics:
        enabled: true
        httpPort: 9090
      grpc:
        maxRetryCount: 6
        initialBackoffSeconds: 10
        maxBackoffSeconds: 600
        backoffMultiplier: 1.5
        resolveFQDN: false
    persistenceConfigurations:
      rdbConfigurations:
        default:
          type: postgres95
          configuration:
            hostname: sitewhere-postgresql.sitewhere-system
            port: 5432
            maxConnections: 5
            username: syncope
            password: syncope
      influxDbConfigurations:
        default:
          hostname: sitewhere-influxdb
          port: 8086
          databaseName: tenant_${tenant.id}
      cassandraConfigurations:
        default:
          contactPoints: sitewhere-cassandra
          keyspace: tenant_${tenant.id}
