apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
{{ include "mosquitto.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: default
      protocol: TCP
      name: default
      #nodePort: 30366
    - port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    {{- if .Values.monitoring.sidecar.enabled }}
    - port: {{ .Values.monitoring.sidecar.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
    {{- end }}      
    - name: tcp-bridge
      port: 10001
      protocol: TCP
      targetPort: 10001
    - name: grpc-bridge
      port: 18080
      protocol: TCP
      targetPort: 18080    
  selector:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
