apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewhere-operator
  labels:
    app: sitewhere
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - instances
  - microservices
  - tenants
  - tenantengines
  verbs:
  - "*"
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instanceconfigurations  
  - instancedatasets
  - tenantconfigurations
  - tenantengineconfigurations
  - tenantdatasets
  - tenantenginedatasets
  verbs:
  - "*"
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - scriptcategories
  - scripttemplates
  - scripts
  - scriptversions 
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "get"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - secrets
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - "get"
  - "watch"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - ingresses
  - networkpolicies
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - "*"