# Use this values to install SiteWhere using rook-ceph-block storageClass
# usage: helm install  sitewhere -f values-rook-ceph.values sitewhere/sitewhere

sitewhere-infra-core:
  cp-kafka:
    persistence:
      storageClass: rook-ceph-block
  cp-zookeeper:
    persistence:
      dataDirStorageClass: rook-ceph-block
      dataLogDirStorageClass: rook-ceph-block
  postgresql:
    persistence:
      storageClass: rook-ceph-block
      
sitewhere-infra-database: 
  mongodb:
    persistence:
      storageClass: rook-ceph-block
  cassandra:
    persistence:
      storageClass: rook-ceph-block
  influxdb:
    persistence:
      storageClass: rook-ceph-block
