# SiteWhere Microservice Settings
microservices:
  default:
    replicas: 1
    service:
      type: LoadBalancer
docker:
  imageRegistry: docker.io
  imageRepository: sitewhere
  imageTag: 3.0.0.alpha1
  imagePullPolicy: IfNotPresent
