# Use this values to install SiteWhere on EKS
# usage: helm install  sitewhere -f values-eks.yaml sitewhere/sitewhere

sitewhere-infra-core:
  kafka:
    persistence:
      storageClass: gp2
    zookeeper:
      persistence:
        storageClass: gp2
sitewhere-infra-database:
  mongodb:
    persistence:
      storageClass: gp2
  cassandra:
    persistence:
      storageClass: gp2
  influxdb:
    persistence:
      storageClass: gp2
