apiVersion: v1
name: warp10
version: 0.2.1
appVersion: 2.2.0
description: Warp 10 is a platform designed to collect, store and analyze sensor and Time Series data. Warp 10™ is both a Time Series Database and an associated analytics environment.
keywords:
- warp10
- database
- timeseries
home: https://www.warp10.io
sources:
- https://github.com/sitewhere/sitewhere-k8s/
maintainers:
- name: jorgevillaverde-sitewhere
  email: jorge.villaverde@sitewhere.com
