apiVersion: infra.sitewhere.io/v1alpha3
kind: InfraCatalogItem
metadata:
  name: apache-nifi
  labels:
    infra.sitewhere.io/catalog: default-catalog
spec:
  name: Apache Nifi
  description: Apache Nifi integration layer
  parentCatalogItemGroupId: integration
  helm:
    repositoryUrl: https://influxdata.github.io/helm-charts
    chartName: influxdb
    chartVersion: 4.8.1
  defaultConfiguration:
    image:
      repository: sitewhere/sitewhere-nifi
      tag: 3.0.0
    service:
      httpPort: 9090
      httpsPort: 9443
    persistence:
      enabled: true
      flowfileRepoStorage:
        size: 1Gi
      contentRepoStorage:
        size: 1Gi
      provenanceRepoStorage:
        size: 1Gi
      logStorage:
        size: 1Gi
    zookeeper:
      replicaCount: 1
      terminationGracePeriodSeconds: 20
  allowMultiple: true
  