apiVersion: infra.sitewhere.io/v1alpha3
kind: InfraCatalogItem
metadata:
  name: mosquitto
  labels:
    infra.sitewhere.io/catalogitemgroup: messaging
spec:
  name: Mosquitto
  description: Mosquitto MQTT broker
  helm:
    repositoryUrl: https://halkeye.github.io/helm-charts
    chartName: mosquitto
    chartVersion: 0.2.0
  defaultConfiguration: {}
  allowMultiple: true
  