apiVersion: infra.sitewhere.io/v1alpha3
kind: InfraCatalogItem
metadata:
  name: postgres
  labels:
    infra.sitewhere.io/catalogitemgroup: relational-database
spec:
  name: PostgreSQL
  description: PostgreSQL instance for relational database persistence
  helm:
    repositoryUrl: https://kubernetes-charts.storage.googleapis.com
    chartName: postgresql
    chartVersion: 8.6.4
  defaultConfiguration:
    image:
      debug: true
    fullnameOverride: sitewhere-postgresql
    enabled: true
    persistence:
      enabled: true
      size: 500Mi
    postgresqlUsername: syncope
    postgresqlDatabase: syncope
    existingSecret: syncope
    service:
      type: LoadBalancer
      port: 5432
    master:
      podAnnotations: 
        sidecar.istio.io/inject: "false"
  allowMultiple: true
  