apiVersion: scripting.sitewhere.io/v1alpha4
kind: SiteWhereScriptCategory
metadata:
  name: event-sources-event-decoder-category
  labels:
    sitewhere.io/functional-area: event-sources
spec:
  name: Event Decoder
  description: Templates for decoding payloads into SiteWhere events
