apiVersion: templates.sitewhere.io/v1alpha4
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-outbound-connectors
  labels:
      sitewhere.io/functional-area: outbound-connectors
spec:
  configuration:
    outboundConnectors:
      - id: mqtt1
        type: mqtt
        configuration:
          hostname: sitewhere-mosquitto.sitewhere-system
          port: 1883
          topic: SiteWhere/${tenant.token}/output/mqtt
