apiVersion: templates.sitewhere.io/v1alpha4
kind: TenantEngineConfigurationTemplate
metadata:
  name: default-event-sources
  labels:
      sitewhere.io/functional-area: event-sources
spec:
  configuration:
    eventSources:
      - id: json
        type: mqtt
        decoder:
          type: json
          configuration: {}
        configuration:
          hostname: sitewhere-mosquitto.sitewhere-system
          port: 1883
          topic: SiteWhere/${tenant.token}/input/json
          numThreads: 3
      - id: protobuf
        type: mqtt
        decoder:
          type: protobuf
          configuration: {}
        configuration:
          hostname: sitewhere-mosquitto.sitewhere-system
          port: 1883
          topic: SiteWhere/${tenant.token}/input/protobuf
          numThreads: 3
