apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sitewhere-leader-election-rolebinding
  labels:
    control-plane: controller-manager
    app: sitewhere
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sitewhere-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: sitewhere-system
