apiVersion: v1
kind: Secret
metadata:
  name: sitewhere
  labels:
    app: sitewhere
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-password: c2l0ZXdoZXJl
  redis-password: c2l0ZXdoZXJl