apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: catalogs.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: InfraCatalog
    listKind: InfraCatalogList
    plural: catalogs
    singular: catalog
    shortNames:
    - swcat
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: catalogitemgroups.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: InfraCatalogItemGroup
    listKind: InfraCatalogItemGroupList
    plural: catalogitemgroups
    singular: catalogitemgroup
    shortNames:
    - swcig
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: catalogitems.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: InfraCatalogItem
    listKind: InfraCatalogItemList
    plural: catalogitems
    singular: catalogitem
    shortNames:
    - swci
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            helm: 
              type: object
              properties:
                repositoryUrl: 
                  type: string
                chartName: 
                  type: string
                chartVersion: 
                  type: string
            defaultConfiguration:
              type: object
            allowMultiple:
              type: boolean
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infrastructures.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: SiteWhereInfrastructure
    listKind: SiteWhereInfrastructureList
    plural: infrastructures
    singular: infrastructure
    shortNames:
    - swinfra
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              activeConfiguration: string
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configurations.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: InfraConfiguration
    listKind: InfraConfigurationList
    plural: configurations
    singular: configuration
    shortNames:
    - swconf
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: InfraComponent
    listKind: InfraComponentList
    plural: components
    singular: component
    shortNames:
    - swcomp
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            configuration:
              type: object
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mscatalogs.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: MicroserviceCatalog
    listKind: MicroserviceCatalogList
    plural: mscatalogs
    singular: mscatalog
    shortNames:
    - swmscat
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mscatalogitemgroups.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: MicroserviceCatalogItemGroup
    listKind: MicroserviceCatalogItemGroupList
    plural: mscatalogitemgroups
    singular: mscatalogitemgroup
    shortNames:
    - swmscig
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
        status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mscatalogitems.infra.sitewhere.io
  labels:
    app: sitewhere
spec:
  group: infra.sitewhere.io
  names:
    kind: MicroserviceCatalogItem
    listKind: MicroserviceCatalogItemList
    plural: mscatalogitems
    singular: mscatalogitem
    shortNames:
    - swmsci
    categories:
    - sitewhere-io
    - infra-sitewhere-io
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1alpha3
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            helm: 
              type: object
              properties:
                repositoryUrl: 
                  type: string
                chartName: 
                  type: string
                chartVersion: 
                  type: string
            defaultConfiguration:
              type: object
            allowMultiple:
              type: boolean
        status: {}
