apiVersion: v2
appVersion: "2.1.1"
description: Helm chart for SiteWhere core infrastructure components
name: sitewhere-infra-core
version: 0.2.8
keywords:
  - sitewhere
  - internet-of-things
  - open-source
  - iot
  - iot-framework
  - iot-platform
  - platform
  - integration
  - microservices
  - device-management
  - mqtt
  - java
  - arduino
  - raspberry-pi
  - android
  - kafka
  - zookeeper
home: https://sitewhere.io/
maintainers:
  - name: Derek Adams
    email: derek.adams@sitewhere.com
  - name: Jorge Villaverde
    email: jorge.villaverde@sitewhere.com
icon: http://sitewhere.io/docs/2.0.0/images/favicon.png
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: sitewhere-infra-core.postgresql.enabled, postgresql.enabled
