apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitewhere-instance-clusterrole-{{ .Release.Namespace }}
  labels:
    app: sitewhere
rules:
- apiGroups:
  - sitewhere.io
  resources:
  - instances
  - microservices
  - tenants
  - tenantengines
  verbs:
  - "*"
- apiGroups:
  - templates.sitewhere.io
  resources:
  - instanceconfigurations  
  - instancedatasets
  - tenantconfigurations
  - tenantengineconfigurations
  - tenantdatasets
  - tenantenginedatasets
  verbs:
  - "*"
- apiGroups:
  - scripting.sitewhere.io
  resources:
  - scriptcategories
  - scripttemplates
  - scripts
  - scriptversions 
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
  