apiVersion: sitewhere.io/v1alpha3
kind: SiteWhereMicroservice
metadata:
  name: instance-management-microservice
{{include "sitewhere.microservice.metadata" . | indent 2 }}
  labels:
{{include "sitewhere.microservice.labels" . | indent 4 }}
    sitewhere.io/functional-area: instance-management
spec:
  replicas: {{ .Values.microservices.default.replicas | default 1 }}
  configuration:
    example: 234
{{include "sitewhere.helm.environment" . | indent 2 }}
  podSpec:
{{include "sitewhere.docker.environment" . | indent 4 }}
    ports:
      - containerPort: 8080
      - containerPort: 9000
      - containerPort: 9090
    env:
{{include "sitewhere.microservice.environment" . | indent 6 }}
      - name: "sitewhere.config.syncope.host"
        value: "sitewhere-syncope"
      - name: "sitewhere.config.syncope.port"
        value: "8080"
  serviceSpec:
{{include "sitewhere.microservice.service" . | indent 4 }}
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: http-rest
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: grpc-api
      - port: 9090
        targetPort: 9090
        protocol: TCP
        name: http-metrics
  debug:
    enabled: false
    jdwpPort: 8001
    jmxPort: 1101
---
apiVersion: v1
kind: Service
metadata:
  name: sitewhere-rest-http
  labels:
    app.kubernetes.io/name: sitewhere
    helm.sh/chart: sitewhere
    app.kubernetes.io/instance: sitewhere
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-rest
  selector:
    sitewhere.io/instance: sitewhere
    sitewhere.io/functional-area: instance-management
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sitewhere-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-rest
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sitewhere-rest
spec:
  hosts:
  - "*"
  gateways:
  - sitewhere-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: sitewhere-rest-http
